// @/lib/activity/favorites.ts
export const favoriteSongs = [
	{ artist: "Hozier", title: "Work Song", startAt: 15 },
	{ artist: "Fleet Foxes", title: "Mykonos", startAt: 15 },
	{ artist: "Hozier", title: "Movement", startAt: 25 },
	{ artist: "David Kushner", title: "Poison", startAt: 20 },
	{ artist: "Gregory Alan Isakov", title: "Southern Star", startAt: 10 },
	{ artist: "David Kushner", title: "No High", startAt: 20 },
	{ artist: "Bennett Woolsey", title: "Jimmy the Chameleon", startAt: 0 },
	{ artist: "David Kushner", title: "Skin and Bones" },
	{ artist: "David Kushner", title: "Dead Man" },
	{ artist: "David Kushner", title: "Sweet Oblivion" },
	{ artist: "David Kushner", title: "Buried at Sea" },
	{ artist: "David Kushner", title: "Darkerside" },
	{ artist: "David Kushner", title: "Saving Your Soul" },
	{ artist: "David Kushner", title: "Daylight" },
	{ artist: "Hozier", title: "Take Me to Church" },
	{ artist: "Hozier", title: "Cherry Wine" },
	{ artist: "Hozier", title: "From Eden" },
	{ artist: "Hozier", title: "Jackie and Wilson" },
	{ artist: "Hozier", title: "Someone New" },
	{ artist: "Hozier", title: "Almost (Sweet Music)" },
	{ artist: "Hozier", title: "Sedated" },
	{ artist: "Hozier", title: "Nina Cried Power" },
	{ artist: "Hozier", title: "Shrike" },
	{ artist: "Hozier", title: "Movement" },
	{ artist: "Hozier", title: "Would That I" },
	{ artist: "Hozier", title: "Dinner & Diatribes" },
	{ artist: "Hozier", title: "Talk" },
	{ artist: "Hozier", title: "Francesca" },
	{ artist: "Hozier", title: "Swan Upon Leda" },
	{ artist: "Hozier", title: "Butchered Tongue" },
	{ artist: "Hozier", title: "Eat Your Young" },
	{ artist: "Hozier", title: "De Selby (Part 1)" },
	{ artist: "Hozier", title: "De Selby (Part 2)" },
	{ artist: "Hozier", title: "Too Sweet" },
	{ artist: "Hozier", title: "First Time" },
	{ artist: "Hozier", title: "In the Woods Somewhere" },
	{ artist: "Hozier", title: "It Will Come Back" },
	{ artist: "Hozier", title: "Foreigner's God" },
	{ artist: "Gregory Alan Isakov", title: "San Luis" },
	{ artist: "The Oh Hellos", title: "Thus Always To Tyrants" },
	{ artist: "Ryan Harris", title: "My Mind" },
	{ artist: "Israel Cannan", title: "Out to Sea" },
	{ artist: "The Franklin Electric", title: "Answers" },
	{ artist: "Ryan Harris", title: "Gone (Away)" },
	{ artist: "Jon and Roy", title: "Runner" },
	{ artist: "Hans Williams", title: "All Is Well" },
	{ artist: "Ryan Harris", title: "Now You Know Me" },
	{ artist: "The Native", title: "Halfway House" },
	{ artist: "Stu Larsen", title: "Thirteen Sad Farewells" },
	{ artist: "Ryan Harris", title: "Sundays" },
	{ artist: "Jon and Roy", title: "Mountain Town" },
	{ artist: "Jonah Kagen", title: "The Roads" },
	{ artist: "Ryan Harris", title: "Same Sun" },
	{ artist: "Ryan Harris", title: "Falling" },
	{ artist: "Ryan Harris", title: "Guide You Home" },
	{ artist: "Ryan Harris", title: "One Day" },
	{ artist: "Ryan Harris", title: "Roam" },
	{ artist: "Freyr, Austin Basham", title: "Wilderness" },
	{ artist: "Paper Planes", title: "Something More" },
	{ artist: "Ryan Harris", title: "Lights Fall" },
	{ artist: "Ryan Harris", title: "Running" },
	{ artist: "Layup", title: "Right Next To You" },
	{ artist: "Twin Tacoma", title: "Weightless" },
	{ artist: "Woodlock", title: "Quick Hands" },
	{ artist: "Paper Planes", title: "Radio Up" },
	{ artist: "Tay Oskee", title: "I Miss It" },
	{ artist: "Salt Tree, Ryan Edmond", title: "Cold Ways" },
	{ artist: "Hollow Coves", title: "Coastline" },
	{ artist: "The Oh Hellos", title: "Soldier, Poet, King" },
	{ artist: "TALK", title: "Run Away to Mars" },
	{ artist: "Vance Joy", title: "Riptide" },
	{ artist: "Zach Bryan, The Lumineers", title: "Spotless (feat. The Lumineers)" },
	{ artist: "Jack and the Weatherman", title: "Till The Sun Comes Up" },
	{ artist: "Stu Larsen", title: "Paper Sails" },
	{ artist: "Passenger, Boy & Bear", title: "Shape of Love" },
	{ artist: "Mt Warning", title: "Sinking Sun (Acoustic Version)" },
	{ artist: "Hollow Coves", title: "The Woods" },
	{ artist: "Gregory Alan Isakov", title: "Big Black Car" },
	{ artist: "The Lumineers", title: "Flowers in Your Hair" },
	{ artist: "The Lumineers", title: "WHERE WE ARE" },
	{ artist: "Brookside", title: "Jimmy the Chameleon" },
	{ artist: "Michael Marcagi", title: "Scared To Start" },
	{ artist: "Winterbourne", title: "Steady My Bones" },
	{ artist: "Sons Of The East", title: "California" },
	{ artist: "Sons Of The East", title: "My Repair" },
	{ artist: "Racoma", title: "Country" },
	{ artist: "Jack and the Weatherman", title: "Free" },
	{ artist: "The Paper Kites", title: "Bloom - Bonus Track" },
	{ artist: "Sandro Cavazza", title: "Lean On Me" },
	{ artist: "Noah Kahan", title: "Passenger" },
	{ artist: "The Oh Hellos", title: "Hello My Old Heart" },
	{ artist: "The Oh Hellos", title: "Constellations" },
	{ artist: "The Oh Hellos", title: "Bitter Water" },
	{ artist: "The Band Willa", title: "Follow Me" },
	{ artist: "New West", title: "Those Eyes" },
	{ artist: "Winterbourne", title: "The Boy Prince" },
	{ artist: "The Paper Kites", title: "Featherstone" },
	{ artist: "Woodlock", title: "I Loved You Then (And I Love You Still)" },
	{ artist: "Ryan Harris", title: "Where You Go" },
	{ artist: "Stu Larsen, Marla", title: "Who's Gonna Catch Me" },
	{ artist: "Oliver Hazard", title: "Dandelion" },
	{ artist: "Oliver Hazard", title: "Grenadine" },
	{ artist: "Steinza", title: "The Former" },
	{ artist: "Darren Kiely", title: "Sunrise" },
	{ artist: "Ryan Harris", title: "Lifeline" },
	{ artist: "Vian Izak, Juniper Vale", title: "Mostly" },
	{ artist: "Daniel Leggs", title: "crutches" },
	{ artist: "Gregory Alan Isakov", title: "Amsterdam" },
	{ artist: "Ryan Harris, The National Forest", title: "Bound to Roam" },
	{ artist: "This New Light", title: "The Mountains" },
	{ artist: "Hayden Calnin", title: "Warm with You" },
	{ artist: "Gregory Alan Isakov", title: "Time Will Tell" },
	{ artist: "Ripto", title: "Icarus & Apollo" },
	{ artist: "Gregory Alan Isakov", title: "O' City Lights" },
	{ artist: "Oliver Hazard", title: "Wild Eyed Blue" },
	{ artist: "Harbor & Home", title: "Blueberry Skies" },
	{ artist: "Noah Kahan", title: "False Confidence" },
	{ artist: "Hollow Coves", title: "Home" }
];
