// lib/widget/album.ts
export const album = [
	{ artist: "Sergei Rachmaninoff", title: "Piano Concerto No. 3, 1st Movement" },
	{ artist: "Sergei Rachmaninoff", title: "Piano Concerto No. 2, 1st Movement" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 23 (Appassionata), 1st Movement" },
	{ artist: "Franz Liszt", title: "Hungarian Rhapsody No. 2" },
	{ artist: "Frédéric Chopin", title: "Polonaise in A-flat Major (Heroic)" },
	{ artist: "Sergei Prokofiev", title: "Piano Concerto No. 2, 1st Movement" },
	{ artist: "Franz Liszt", title: "Mephisto Waltz No. 1" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 21 (Waldstein), 1st Movement" },
	{ artist: "Sergei Rachmaninoff", title: "Piano Concerto No. 3, 3rd Movement" },
	{ artist: "Frédéric Chopin", title: "Scherzo No. 2 in B-flat Minor" },
	{ artist: "Franz Liszt", title: "Totentanz" },
	{ artist: "Modest Mussorgsky", title: "Pictures at an Exhibition: The Great Gate of Kiev" },
	{ artist: "Sergei Rachmaninoff", title: "Rhapsody on a Theme of Paganini, Var. 18" },
	{ artist: "Frédéric Chopin", title: "Etude Op. 10 No. 12 (Revolutionary)" },
	{ artist: "Franz Liszt", title: "Piano Sonata in B Minor" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 8 (Pathétique), 1st Movement" },
	{ artist: "Sergei Prokofiev", title: "Piano Sonata No. 7, 3rd Movement (Precipitato)" },
	{ artist: "Wolfgang Amadeus Mozart", title: "Piano Concerto No. 20, 1st Movement" },
	{ artist: "Sergei Rachmaninoff", title: "Piano Concerto No. 2, 3rd Movement" },
	{ artist: "Franz Liszt", title: "La Campanella" },
	{ artist: "Dmitri Shostakovich", title: "Piano Concerto No. 2, 1st Movement" },
	{ artist: "Frédéric Chopin", title: "Ballade No. 1 in G Minor" },
	{ artist: "Edvard Grieg", title: "Piano Concerto in A Minor, 1st Movement" },
	{ artist: "Franz Liszt", title: "Hungarian Rhapsody No. 6" },
	{ artist: "Sergei Rachmaninoff", title: "Prelude in G Minor, Op. 23 No. 5" },
	{ artist: "Ludwig van Beethoven", title: "Piano Concerto No. 5 (Emperor), 1st Movement" },
	{ artist: "Frédéric Chopin", title: "Etude Op. 25 No. 11 (Winter Wind)" },
	{ artist: "Modest Mussorgsky", title: "Pictures at an Exhibition: Baba Yaga" },
	{ artist: "Sergei Prokofiev", title: "Toccata in D Minor, Op. 11" },
	{ artist: "George Gershwin", title: "Rhapsody in Blue" },
	{ artist: "Franz Liszt", title: "Grandes Études de Paganini No. 6" },
	{ artist: "Pyotr Ilyich Tchaikovsky", title: "Piano Concerto No. 1, 1st Movement" },
	{ artist: "Sergei Rachmaninoff", title: "Piano Sonata No. 2, 1st Movement" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 32, 1st Movement" },
	{ artist: "Franz Liszt", title: "Transcendental Étude No. 4 (Mazeppa)" },
	{ artist: "Frédéric Chopin", title: "Fantaisie-Impromptu" },
	{ artist: "Sergei Prokofiev", title: "Piano Concerto No. 3, 1st Movement" },
	{ artist: "Johannes Brahms", title: "Piano Concerto No. 1, 1st Movement" },
	{ artist: "Franz Liszt", title: "Réminiscences de Don Juan" },
	{ artist: "Dmitri Shostakovich", title: "Piano Concerto No. 1, 4th Movement" },
	{ artist: "Sergei Rachmaninoff", title: "Etudes-Tableaux, Op. 39 No. 5" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 17 (Tempest), 3rd Movement" },
	{ artist: "Frédéric Chopin", title: "Andante Spianato et Grande Polonaise Brillante" },
	{ artist: "Franz Liszt", title: "Hungarian Rhapsody No. 15 (Rákóczi March)" },
	{ artist: "Aram Khachaturian", title: "Sabre Dance (piano arrangement)" },
	{ artist: "Sergei Rachmaninoff", title: "Moment Musical Op. 16 No. 4" },
	{ artist: "Pyotr Ilyich Tchaikovsky", title: "The Seasons: November - Troika" },
	{ artist: "Franz Liszt", title: "Funérailles" },
	{ artist: "Ludwig van Beethoven", title: "Piano Sonata No. 14 (Moonlight), 3rd Movement" },
	{ artist: "Sergei Prokofiev", title: "Suggestion Diabolique" }
];
