import { Project } from "@/app/projects/model";

export const projects: Project[] = [
	{
		id: "collatz-viz",
		rank: 9,
		slug: "collatz-viz",
		title: "Collatz Conjecture Explorer",
		tagline: "Nobody has proved it. here's what it looks like",
		description: "An interactive visualizer for exploring stopping-time patterns in the Collatz Conjecture.",
		tags: ["software engineering"],
		tech: ["Rust", "WebAssembly", "TypeScript", "Vite", "Canvas API", "Web Workers"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/collatz-explorer",
		image: "/images/projects/collatz.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "groat",
		rank: 1,
		slug: "groat",
		title: "groat",
		tagline: "Every token counts.",
		description: "A self-hosted proxy that cuts your LLM API costs through smart caching and model routing.",
		tags: ["systems programming", "machine learning"],
		tech: ["Rust", "Tokio", "LLM-compatible APIs", "Vector databases", "Embeddings", "LLMs", "SQL", "Typescript"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/groat",
		live: "https://getgroat.vercel.app/",
		image: "/images/projects/groat.png",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "mapreduce-engine",
		rank: 10,
		slug: "mapreduce-engine",
		title: "creduce",
		tagline: "Hadoop is overkill. built it anyway, from scratch.",
		description: "A MapReduce engine built from scratch, handling the full map-shuffle-reduce pipeline without Hadoop.",
		tags: ["systems programming", "data engineering"],
		tech: ["C", "pthreads", "Make", "GCC"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/creduce",
		image: "/images/projects/creduce.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "calvin-hobbes-api",
		rank: 8,
		slug: "calvin-hobbes-api",
		title: "Calvin & Hobbes Quote API",
		tagline: "Philosophy from a six-year-old, on demand",
		description: "A simple API that serves up Calvin and Hobbes quotes for any app that needs some personality.",
		tags: ["software engineering"],
		tech: ["Python", "Flask", "Vercel", "Git", "Rest API"],
		status: "completed",
		year: 2024,
		github: "https://github.com/bhavv04/calandhobbes-quoter",
		live: "https://calandhobbes-quoter-7gd9mxl0e-bhavdeeps-projects.vercel.app/api/quotes/random",
		image: "/images/projects/calandhobbes.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "thunderhead",
		rank: 2,
		slug: "thunderhead",
		title: "Thunderhead",
		tagline: "Silent observation. no captchas. no cloudflare.",
		description: "A reverse proxy that quietly detects and blocks bot traffic without CAPTCHAs or user friction.",
		tags: ["systems programming", "software engineering"],
		tech: ["Go", "net/http", "httputil.ReverseProxy", "Bubbletea", "Lipgloss", "Next.js", "Docker", "ngrok"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/thunderhead",
		live: "https://getthunderhead.vercel.app/",
		image: "/images/projects/thunderhead.png",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "verrere",
		rank: 4,
		slug: "verrere",
		title: "Verrere",
		tagline: "Discover your next read. Swipe right to build your bookshelf",
		description: "A swipe-based book discovery app that learns your taste and builds your reading list.",
		tags: ["software engineering", "data engineering"],
		tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "Framer Motion", "Clerk", "Neon", "Prisma", "PostgreSQL"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/verrere",
		live: "https://verrere.vercel.app/",
		image: "/images/projects/verrere.png",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "funes",
		rank: 3,
		slug: "funes",
		title: "funes",
		tagline: "Your machine's memory, queryable.",
		description: "A local-only tool that indexes your files and terminal history so you can search your past work in plain English.",
		tags: ["systems programming", "machine learning", "data engineering", "software engineering"],
		tech: ["Rust", "Ollama", "SQLite", "cargo", "Tokio", "Clap", "Vector databases", "LLMs"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/funes",
		image: "/images/projects/funes.png",
		live: "https://get-funes.vercel.app/",
		featured: true,
		hasCaseStudy: true
	},
	{
		id: "ember",
		rank: 6,
		slug: "ember",
		title: "Ember",
		tagline: "Not a calorie tracker. a deficit visualizer.",
		description: "A weight-loss planner that visualizes your calorie deficit and projects when you'll hit your goal.",
		tags: ["software engineering"],
		tech: ["Next.js 15", "TypeScript", "Tailwind CSS", "shadcn/ui", "Clerk", "Neon", "Prisma", "PostgreSQL"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/ember",
		live: "https://myember.vercel.app/",
		image: "/images/projects/ember.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "quillith",
		rank: 14,
		slug: "quillith",
		title: "Quillith",
		tagline: "A place to write the story.",
		description: "A writing workspace for authors to organize chapters, characters, and their whole manuscript in one place.",
		tags: ["software engineering"],
		tech: ["TypeScript", "Next.js", "React", "Tailwind CSS"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/quillith",
		live: "",
		image: "/images/projects/quillith.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "wattson",
		rank: 11,
		slug: "wattson",
		title: "Wattson",
		tagline: "Tuning GPU kernels for more than just speed.",
		description: "A GPU kernel tuner that optimizes for power efficiency, not just raw speed.",
		tags: ["systems programming", "machine learning"],
		tech: ["CUDA", "C++", "Python", "nvidia-smi", "GPU kernels", "Autotuning"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/wattson",
		live: "",
		image: "/images/projects/wattson.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "terraseed",
		rank: 7,
		slug: "terraseed",
		title: "Terraseed",
		tagline: "30 years of climate data, one planting score",
		description: "Uses decades of climate data to predict the best planting windows for any crop, anywhere on Earth.",
		tags: ["machine learning", "data engineering", "data visualization"],
		tech: ["Python", "Plotly Dash", "scikit-learn", "xarray"],
		status: "active",
		year: 2025,
		github: "https://github.com/bhavv04/terraseed",
		image: "/images/projects/terraseed.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "redis-c",
		rank: 13,
		slug: "redis-c",
		title: "Custom Redis",
		tagline: "Redis, from scratch, in C.",
		description: "A Redis-compatible in-memory key-value store built from the ground up.",
		tags: ["systems programming"],
		tech: ["C", "POSIX sockets", "RESP protocol", "Make"],
		status: "completed",
		year: 2026,
		github: "https://github.com/bhavv04/redis",
		live: "",
		image: "/images/projects/redis.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "gaia",
		rank: 7,
		slug: "gaia",
		title: "Gaia",
		tagline: "Cross-domain cascade failure prediction in ecological systems",
		description: "Models how local ecological collapses ripple outward to predict global cascade failures.",
		tags: ["machine learning", "data engineering"],
		tech: ["Python", "NetworkX", "PyTorch Geometric", "xarray", "GeoPandas"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/gaia",
		image: "/images/projects/gaia.png",
		featured: true,
		hasCaseStudy: false
	},
	{
		id: "awkrs",
		rank: 12,
		slug: "awkrs",
		title: "GNU AWK in rust",
		tagline: "awk, rewritten in Rust, without the archaeology",
		description: "A modern rewrite of the AWK text-processing language in Rust, built with memory safety in mind.",
		tags: ["systems programming"],
		tech: ["Rust"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/awk-rs",
		live: "",
		image: "/images/projects/awkrs.png",
		featured: false,
		hasCaseStudy: false
	},
	{
		id: "solace",
		rank: 5,
		slug: "solace",
		title: "Solace",
		tagline: "Predicting wildfire spread, not just visualizing it.",
		description: "A wildfire spread simulator that models real fire behavior, validated against the 2016 Fort McMurray fire.",
		tags: ["systems programming", "data visualization", "data engineering", "computer vision"],
		tech: ["Rust", "Python", "GeoPandas", "Rasterio", "xarray", "ERA5", "Canadian FBP System", "Fire Weather Index (FWI)", "GIS"],
		status: "active",
		year: 2026,
		github: "https://github.com/bhavv04/solace",
		live: "",
		image: "/images/projects/solace.png",
		featured: true,
		hasCaseStudy: false
	}
];
